###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"jagadish",
    "username":"jagadish789",
    "password": "jagadish@8106",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"jagadish789",
    "password": "jagadish@8106"
}